# Generated by Django 5.2.16 on 2026-08-10 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0002_alter_datasetupload_tipo'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='código')),
                ('nombre', models.TextField()),
                ('origen', models.CharField(choices=[('actividad', 'Actividad del programa'), ('proyecto', 'Proyecto de inversión')], db_index=True, max_length=10)),
                ('automatico', models.BooleanField(default=True, help_text='Lo puso la semilla o el importador. Al guardarlo desde el admin se desmarca: a partir de ahí la asignación es de PREDES y nada la sobrescribe.', verbose_name='asignado automáticamente')),
            ],
            options={
                'verbose_name': 'clasificación de actividad',
                'verbose_name_plural': 'clasificación de actividades (procesos de la GRD)',
                'ordering': ['origen', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('anio', models.PositiveSmallIntegerField(unique=True, verbose_name='año')),
                ('corte', models.CharField(default='anual', help_text="'anual' para un ejercicio cerrado; 'AAAA-MM' para un corte a mitad de año.", max_length=10)),
                ('fuente', models.CharField(choices=[('MEF', 'Consulta Amigable / comparativo del MEF'), ('BASE_PP0068', 'Base PP 0068 entregada por PREDES')], default='MEF', max_length=20)),
                ('es_parcial', models.BooleanField(default=False, help_text='El devengado no cubre el año entero. La ventana lo advierte y no compara su % de ejecución con el de un ejercicio cerrado.', verbose_name='es parcial')),
                ('fecha_corte', models.DateField(blank=True, null=True)),
                ('visible', models.BooleanField(default=False, help_text='Interruptor de la ventana: sin ningún ejercicio visible, /inversion muestra su estado «información en preparación».')),
            ],
            options={
                'verbose_name': 'ejercicio presupuestal',
                'verbose_name_plural': 'ejercicios presupuestales',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoGRD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=40, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('color', models.CharField(blank=True, help_text='Hex, para los gráficos.', max_length=7)),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
            ],
            options={
                'verbose_name': 'proceso de la GRD',
                'verbose_name_plural': 'procesos de la GRD',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='EntidadEjecutora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='código MEF')),
                ('nombre', models.CharField(max_length=200)),
                ('ambito', models.CharField(choices=[('distrital', 'Municipalidad distrital'), ('provincial', 'Municipalidad provincial'), ('mancomunidad', 'Mancomunidad municipal'), ('regional', 'Gobierno regional'), ('nacional', 'Gobierno nacional')], db_index=True, max_length=12, verbose_name='ámbito')),
                ('distrito', models.ForeignKey(blank=True, help_text='Distrito sede. Para una municipalidad provincial es su capital, no su ámbito.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_ejecutoras', to='territorio.distrito', to_field='ubigeo')),
                ('provincia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entidades_ejecutoras', to='territorio.provincia', to_field='ubigeo')),
            ],
            options={
                'verbose_name': 'entidad ejecutora',
                'verbose_name_plural': 'entidades ejecutoras',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PresupuestoActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pia', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('pim', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('devengado', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('clasificacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuestos', to='inversion.clasificacionactividad')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='inversion.ejercicio')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='inversion.entidadejecutora')),
            ],
            options={
                'verbose_name': 'presupuesto por actividad',
                'verbose_name_plural': 'presupuestos por actividad',
            },
        ),
        migrations.CreateModel(
            name='PresupuestoEntidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('pia', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='PIA del 0068')),
                ('pim', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='PIM del 0068')),
                ('devengado', models.DecimalField(decimal_places=2, default=0, max_digits=16, verbose_name='devengado del 0068')),
                ('pia_institucional', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('pim_institucional', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('devengado_institucional', models.DecimalField(blank=True, decimal_places=2, max_digits=16, null=True)),
                ('dataset_upload', models.ForeignKey(blank=True, help_text='Carga que trajo este dato (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presupuestos', to='datasets.datasetupload')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='inversion.ejercicio')),
                ('entidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='inversion.entidadejecutora')),
            ],
            options={
                'verbose_name': 'presupuesto por entidad',
                'verbose_name_plural': 'presupuestos por entidad',
            },
        ),
        migrations.AddField(
            model_name='clasificacionactividad',
            name='proceso',
            field=models.ForeignKey(blank=True, help_text='Vacío = sin clasificar. Su importe se muestra aparte, nunca repartido.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='actividades', to='inversion.procesogrd'),
        ),
        migrations.AddIndex(
            model_name='entidadejecutora',
            index=models.Index(fields=['ambito', 'provincia'], name='inversion_e_ambito_2649db_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestoactividad',
            index=models.Index(fields=['ejercicio', 'entidad'], name='inversion_p_ejercic_a7bfcf_idx'),
        ),
        migrations.AddIndex(
            model_name='presupuestoactividad',
            index=models.Index(fields=['ejercicio', 'clasificacion'], name='inversion_p_ejercic_e8cddc_idx'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoactividad',
            constraint=models.UniqueConstraint(fields=('ejercicio', 'entidad', 'clasificacion'), name='unico_presupuesto_ejercicio_entidad_actividad'),
        ),
        migrations.AddIndex(
            model_name='presupuestoentidad',
            index=models.Index(fields=['ejercicio', 'entidad'], name='inversion_p_ejercic_e8b63e_idx'),
        ),
        migrations.AddConstraint(
            model_name='presupuestoentidad',
            constraint=models.UniqueConstraint(fields=('ejercicio', 'entidad'), name='unico_presupuesto_ejercicio_entidad'),
        ),
        migrations.AddIndex(
            model_name='clasificacionactividad',
            index=models.Index(fields=['proceso', 'origen'], name='inversion_c_proceso_b043b2_idx'),
        ),
    ]
