# Generated by Django 5.2.16 on 2026-08-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inversion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='fuente',
            field=models.CharField(choices=[('MEF', 'Consulta Amigable / comparativo del MEF'), ('BASE_PP0068', 'Base PP 0068 desarrollada por PREDES')], default='MEF', max_length=20),
        ),
    ]
