# Generated by Django 5.2.16 on 2026-08-03 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'categoría de documento',
                'verbose_name_plural': 'categorías de documento',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.', verbose_name='nota de revisión')),
                ('titulo', models.CharField(max_length=300)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='biblioteca/%Y/%m/')),
                ('url_externa', models.URLField(blank=True, null=True, verbose_name='enlace externo')),
                ('resumen', models.TextField(blank=True)),
                ('resumen_generado_por_ia', models.BooleanField(default=False, verbose_name='resumen generado por IA')),
                ('autor_institucion', models.CharField(blank=True, max_length=200, verbose_name='autor o institución')),
                ('fecha_publicacion', models.DateField(blank=True, null=True, verbose_name='fecha de publicación')),
                ('ia_estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Generado'), ('error', 'Error')], default='pendiente', max_length=12, verbose_name='estado de la IA')),
                ('log_ia', models.TextField(blank=True, verbose_name='registro de la IA')),
                ('portada', models.ImageField(blank=True, null=True, upload_to='biblioteca/portadas/')),
                ('paginas', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peso_bytes', models.PositiveBigIntegerField(blank=True, editable=False, null=True)),
                ('descargas', models.PositiveIntegerField(default=0, editable=False)),
                ('idioma', models.CharField(blank=True, default='es', max_length=20)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='biblioteca.categoriadocumento')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'documento',
                'ordering': ['-fecha_publicacion', '-creado_en'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar documentos')],
                'constraints': [models.CheckConstraint(condition=models.Q(('archivo', ''), ('url_externa__isnull', True), _negated=True), name='documento_con_archivo_o_url')],
            },
        ),
    ]
