# Generated by Django 5.2.16 on 2026-08-03 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ubigeo', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('poblacion_censo', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'provincia',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ubigeo', models.CharField(db_index=True, max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('nombre_normalizado', models.CharField(db_index=True, editable=False, max_length=100)),
                ('poblacion_censo', models.PositiveIntegerField(blank=True, null=True)),
                ('superficie_km2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('contacto_gdr', models.CharField(blank=True, max_length=200)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='distritos', to='territorio.provincia')),
            ],
            options={
                'verbose_name': 'distrito',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CentroPoblado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='código INEI')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(blank=True, max_length=50)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('altitud', models.IntegerField(blank=True, null=True)),
                ('poblacion', models.PositiveIntegerField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('fuente_padron', models.CharField(blank=True, max_length=100)),
                ('anio_padron', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='centros_poblados', to='territorio.distrito', to_field='ubigeo')),
            ],
            options={
                'verbose_name': 'centro poblado',
                'ordering': ['codigo'],
                'indexes': [models.Index(fields=['distrito', 'nombre'], name='territorio__distrit_8ac889_idx')],
            },
        ),
    ]
