# Generated by Django 5.2.16 on 2026-08-11 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_vaciar_poblacion_sin_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='distrito',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
