# Generated by Django 5.2.16 on 2026-08-03 12:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('datasets', '0001_initial'),
        ('territorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('columna_total', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'verbose_name': 'categoría de evento',
                'verbose_name_plural': 'categorías de evento',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Fuente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(blank=True, max_length=50)),
                ('url_base', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('nombre', models.CharField(help_text='Valor de la columna PELIGRO del Excel, no el título de la hoja.', max_length=100, unique=True)),
                ('hoja_excel', models.CharField(blank=True, help_text='Título de la hoja en el Excel canónico. Lo usa el importador para mapear hoja → peligro; difiere del nombre en Lluvias e Incendios Forestales.', max_length=100)),
                ('categoria_geo', models.CharField(blank=True, help_text='El TIP_PELIG de la fuente (Geodinamica interna/externa, Metereologicas).', max_length=100)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('descripcion', models.TextField(blank=True)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
            ],
            options={
                'verbose_name': 'tipo de peligro',
                'verbose_name_plural': 'tipos de peligro',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('columna_excel', models.CharField(blank=True, max_length=60)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tipos', to='peligros.categoriaevento')),
            ],
            options={
                'verbose_name': 'tipo de evento',
                'verbose_name_plural': 'tipos de evento',
                'ordering': ['categoria__orden', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='FrecuenciaEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('conteo', models.PositiveIntegerField()),
                ('rango_fecha', models.CharField(blank=True, max_length=50)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('fuente_url', models.URLField(blank=True)),
                ('anio_inicio', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('anio_fin', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dataset_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frecuencias', to='datasets.datasetupload')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frecuencias', to='territorio.distrito')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='frecuencias', to='peligros.tipoevento')),
            ],
            options={
                'verbose_name': 'frecuencia de emergencia',
                'verbose_name_plural': 'frecuencias de emergencia',
                'indexes': [models.Index(fields=['distrito'], name='peligros_fr_distrit_48c396_idx'), models.Index(fields=['tipo_evento'], name='peligros_fr_tipo_ev_1eb6ea_idx')],
                'constraints': [models.UniqueConstraint(fields=('distrito', 'tipo_evento'), name='unica_frecuencia_distrito_evento')],
            },
        ),
        migrations.CreateModel(
            name='ClasificacionPeligro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nivel', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('fuente_url', models.URLField(blank=True)),
                ('anio_dato', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('vigente', models.BooleanField(default=True)),
                ('centro_poblado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clasificaciones', to='territorio.centropoblado')),
                ('dataset_upload', models.ForeignKey(blank=True, help_text='Carga que trajo este dato (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clasificaciones', to='datasets.datasetupload')),
                ('fuente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='peligros.fuente')),
                ('tipo_peligro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clasificaciones', to='peligros.tipopeligro')),
            ],
            options={
                'verbose_name': 'clasificación de peligro',
                'verbose_name_plural': 'clasificaciones de peligro',
                'indexes': [models.Index(fields=['tipo_peligro', 'nivel'], name='peligros_cl_tipo_pe_680195_idx'), models.Index(fields=['centro_poblado'], name='peligros_cl_centro__69d050_idx')],
                'constraints': [models.UniqueConstraint(fields=('centro_poblado', 'tipo_peligro'), name='unica_clasificacion_ccpp_peligro'), models.CheckConstraint(condition=models.Q(('nivel__gte', 1), ('nivel__lte', 4)), name='nivel_peligro_entre_1_y_4')],
            },
        ),
        migrations.CreateModel(
            name='TotalDeclaradoEmergencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField()),
                ('rango_fecha', models.CharField(blank=True, max_length=50)),
                ('fuente', models.CharField(blank=True, max_length=100)),
                ('fuente_url', models.URLField(blank=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='totales_declarados', to='peligros.categoriaevento')),
                ('dataset_upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='totales_declarados', to='datasets.datasetupload')),
                ('distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='totales_declarados', to='territorio.distrito')),
            ],
            options={
                'verbose_name': 'total declarado de emergencias',
                'verbose_name_plural': 'totales declarados de emergencias',
                'indexes': [models.Index(fields=['distrito'], name='peligros_to_distrit_be2b28_idx')],
                'constraints': [models.UniqueConstraint(fields=('distrito', 'categoria'), name='unico_total_declarado_distrito_categoria')],
            },
        ),
    ]
