# Generated by Django 5.2.16 on 2026-08-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peligros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipopeligro',
            name='icono',
            field=models.CharField(blank=True, help_text='Nombre del ícono lucide en kebab-case (p. ej. `cloud-rain`). Es la FORMA del símbolo en el visor; el color lo pone el nivel, no el peligro. Si el nombre no existe en la librería, el visor cae en un ícono genérico en vez de romperse.', max_length=50),
        ),
    ]
