# Generated by Django 5.2.16 on 2026-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapaCartografica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(help_text='Nombre de la capa dentro del tile y del archivo .pmtiles (rios, lagunas…).', max_length=60, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo_geojson', models.FileField(upload_to='capas/%Y/%m/')),
                ('tipo_geometria', models.CharField(blank=True, choices=[('punto', 'Puntos'), ('linea', 'Líneas'), ('poligono', 'Polígonos')], editable=False, max_length=10)),
                ('estilo', models.JSONField(blank=True, default=dict, help_text='Paint de MapLibre (color, grosor, opacidad). Permite recolorear la capa sin tocar código, que es el requisito de reemplazo de capas del TDR.')),
                ('min_zoom', models.PositiveSmallIntegerField(default=0)),
                ('max_zoom', models.PositiveSmallIntegerField(blank=True, help_text='Vacío = que tippecanoe lo deduzca (-zg).', null=True)),
                ('filtro_atributo', models.CharField(blank=True, help_text='Recorte por atributo, p. ej. DN99=CUSCO o DPTO ILIKE cusco. Vacío = se recorta espacialmente con el polígono regional.', max_length=120)),
                ('visible_por_defecto', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('atribucion', models.CharField(blank=True, max_length=250)),
                ('fuente', models.CharField(blank=True, max_length=200)),
                ('simplificacion', models.FloatField(blank=True, help_text='Tolerancia de -simplify de ogr2ogr, en grados.', null=True)),
                ('estado_tiles', models.CharField(choices=[('pendiente', 'Pendiente'), ('generando', 'Generando'), ('ok', 'Listo'), ('error', 'Error')], default='pendiente', editable=False, max_length=10)),
                ('pmtiles', models.CharField(blank=True, editable=False, max_length=200)),
                ('log_error', models.TextField(blank=True, editable=False)),
                ('crs_origen', models.CharField(blank=True, editable=False, help_text='CRS detectado en el archivo. Se registra porque hay fuentes proyectadas (glaciares viene en EPSG:32718) y sin reproyectar los tiles salen vacíos.', max_length=40)),
                ('features_generados', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'capa cartográfica',
                'verbose_name_plural': 'capas cartográficas',
                'ordering': ['orden', 'nombre'],
            },
        ),
    ]
