# Generated by Django 5.2.16 on 2026-08-03 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventoUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pageview', 'Visita'), ('descarga_pdf', 'Descarga de ayuda memoria'), ('export_excel', 'Export a Excel'), ('busqueda', 'Búsqueda'), ('descarga_documento', 'Descarga de documento'), ('click_capa', 'Activación de capa del mapa')], max_length=20)),
                ('ruta', models.CharField(db_index=True, max_length=250)),
                ('detalle', models.CharField(blank=True, help_text='Término buscado, ubigeo del informe, slug del documento…', max_length=250)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session_hash', models.CharField(blank=True, max_length=16)),
            ],
            options={
                'verbose_name': 'evento de uso',
                'verbose_name_plural': 'eventos de uso',
                'indexes': [models.Index(fields=['tipo', '-fecha'], name='metricas_ev_tipo_fbf30b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ResumenDiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('pageview', 'Visita'), ('descarga_pdf', 'Descarga de ayuda memoria'), ('export_excel', 'Export a Excel'), ('busqueda', 'Búsqueda'), ('descarga_documento', 'Descarga de documento'), ('click_capa', 'Activación de capa del mapa')], max_length=20)),
                ('ruta', models.CharField(max_length=250)),
                ('detalle', models.CharField(blank=True, max_length=250)),
                ('conteo', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'resumen diario',
                'verbose_name_plural': 'resúmenes diarios',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'tipo', 'ruta', 'detalle'), name='unico_resumen_diario')],
            },
        ),
    ]
