# Generated by Django 5.2.16 on 2026-08-03 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BloqueTexto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('clave', models.SlugField(help_text='P. ej. home.hero.titulo', max_length=80, unique=True)),
                ('titulo', models.CharField(blank=True, max_length=200)),
                ('cuerpo', models.TextField(blank=True, help_text='HTML de CKEditor 5. Se sanea al guardar (ADR-D2).')),
                ('pagina', models.CharField(choices=[('home', 'Portada'), ('sobre', 'Sobre el observatorio'), ('peligros', 'Exposición a peligros'), ('medidas', 'Medidas'), ('normativa', 'Normativa'), ('recursos', 'Recursos'), ('footer', 'Pie de página'), ('general', 'General')], default='general', max_length=12)),
            ],
            options={
                'verbose_name': 'bloque de texto',
                'verbose_name_plural': 'bloques de texto',
                'ordering': ['pagina', 'clave'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionSitio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre_sitio', models.CharField(default='Observatorio Kallpachakuy', max_length=150)),
                ('descripcion_footer', models.TextField(blank=True)),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=60)),
                ('direccion', models.CharField(blank=True, max_length=250)),
                ('redes', models.JSONField(blank=True, default=dict, help_text='P. ej. {"facebook": "https://…"}.')),
                ('mensaje_banner', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='sitio/')),
                ('logo_footer', models.ImageField(blank=True, null=True, upload_to='sitio/')),
            ],
            options={
                'verbose_name': 'configuración del sitio',
                'verbose_name_plural': 'configuración del sitio',
            },
        ),
        migrations.CreateModel(
            name='EnlaceMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('zona', models.CharField(choices=[('header', 'Menú principal'), ('footer', 'Pie de página')], max_length=8)),
                ('texto', models.CharField(max_length=80)),
                ('url', models.CharField(max_length=200)),
                ('grupo', models.CharField(blank=True, help_text='Columna del pie en la que se agrupa (p. ej. «Más»). Vacío en el header.', max_length=60)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'enlace del menú',
                'verbose_name_plural': 'menú',
                'ordering': ['zona', 'orden'],
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.')),
                ('titulo', models.CharField(max_length=200)),
                ('subtitulo', models.CharField(blank=True, max_length=300)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('cta_texto', models.CharField(blank=True, max_length=80, verbose_name='texto del botón')),
                ('cta_url', models.CharField(blank=True, max_length=200, verbose_name='destino del botón')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('vigente_desde', models.DateField(blank=True, null=True)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'slide del hero',
                'verbose_name_plural': 'hero de portada',
                'ordering': ['orden'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar slides del hero')],
            },
        ),
    ]
