# Generated by Django 5.2.16 on 2026-08-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitio', '0002_ocultar_comparar_del_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enlacemenu',
            name='grupo',
            field=models.CharField(blank=True, help_text='Columna del pie en la que se agrupa (p. ej. «Más»). Vacío en top y header.', max_length=60),
        ),
        migrations.AlterField(
            model_name='enlacemenu',
            name='zona',
            field=models.CharField(choices=[('top', 'Barra superior'), ('header', 'Menú principal'), ('footer', 'Pie de página')], max_length=8),
        ),
    ]
