# Generated by Django 5.2.16 on 2026-08-03 12:58

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('peligros', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('inicio', models.DateTimeField(db_index=True)),
                ('fin', models.DateTimeField(blank=True, null=True)),
                ('lugar', models.CharField(blank=True, max_length=250)),
                ('modalidad', models.CharField(choices=[('presencial', 'Presencial'), ('virtual', 'Virtual'), ('mixta', 'Mixta')], default='presencial', max_length=12)),
                ('url_inscripcion', models.URLField(blank=True, null=True)),
                ('organizador', models.CharField(blank=True, max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='eventos/%Y/%m/')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ['inicio'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar eventos')],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField(blank=True)),
                ('url', models.URLField(help_text='Enlace de YouTube o Vimeo.')),
                ('fecha', models.DateField(db_index=True)),
                ('thumbnail_override', models.ImageField(blank=True, null=True, upload_to='videos/')),
                ('duracion', models.CharField(blank=True, max_length=12)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='peligros.tipopeligro')),
            ],
            options={
                'verbose_name': 'video',
                'ordering': ['-fecha'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar videos')],
            },
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=250)),
                ('bajada', models.TextField(max_length=500)),
                ('cuerpo', models.TextField(blank=True, help_text='HTML de CKEditor 5. Se sanea al guardar (ADR-D2).')),
                ('tipo', models.CharField(choices=[('noticia', 'Noticia'), ('articulo', 'Artículo'), ('opinion', 'Opinión')], default='noticia', max_length=10)),
                ('autor', models.CharField(blank=True, max_length=150)),
                ('fecha', models.DateField(db_index=True)),
                ('imagen_portada', models.ImageField(blank=True, help_text='Si lo dejas vacío se usa la ilustración institucional del tipo de contenido.', null=True, upload_to='noticias/%Y/%m/')),
                ('imagen_titulo', models.CharField(blank=True, max_length=300)),
                ('palabras_clave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None)),
                ('destacada', models.BooleanField(default=False, help_text='Aparece en la portada.')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'noticia',
                'ordering': ['-fecha'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar noticias')],
                'indexes': [models.Index(fields=['estado', '-fecha'], name='contenidos__estado_e81f2f_idx')],
            },
        ),
    ]
