# Generated by Django 5.2.16 on 2026-08-28 05:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ['-destacada', '-fecha', '-id'], 'permissions': [('puede_publicar', 'Puede publicar y archivar noticias')], 'verbose_name': 'noticia'},
        ),
        migrations.RemoveIndex(
            model_name='noticia',
            name='contenidos__estado_e81f2f_idx',
        ),
        migrations.AddIndex(
            model_name='noticia',
            index=models.Index(fields=['estado', '-destacada', '-fecha'], name='contenidos__estado_973f6b_idx'),
        ),
    ]
