# Generated by Django 5.2.16 on 2026-08-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0002_alter_noticia_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='ia_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Generado'), ('error', 'Error')], default='pendiente', max_length=12, verbose_name='estado de la IA'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='log_ia',
            field=models.TextField(blank=True, verbose_name='registro de la IA'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='redactada_por_ia',
            field=models.BooleanField(default=False, verbose_name='redactada por IA'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='url_origen',
            field=models.URLField(blank=True, help_text='Página de la que se redactó la noticia. Queda como procedencia.', max_length=500, verbose_name='URL de origen'),
        ),
    ]
