# Generated by Django 5.2.16 on 2026-08-28 18:14

from django.db import migrations, models

# Solo cambia el `help_text`: los cuatro campos de IA de `Noticia` pasaron a venir de
# `core.RedaccionIAMixin`, compartido con `normativa.Norma` (ADR-D8), y su texto dejó de decir
# «la noticia» para decir «la ficha». No toca la base —Postgres no guarda el help_text—, pero
# Django la emite igual, y arrastrarla sin explicación invita a borrarla por error.


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0004_alter_evento_estado_alter_noticia_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='url_origen',
            field=models.URLField(blank=True, help_text='Página de la que se redactó la ficha. Queda como procedencia.', max_length=500, verbose_name='URL de origen'),
        ),
    ]
