# Generated by Django 5.2.16 on 2026-08-31 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0005_alter_noticia_url_origen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='tipo',
            field=models.CharField(choices=[('noticia', 'Noticia'), ('articulo', 'Artículo'), ('opinion', 'Opinión'), ('publicacion', 'Publicación'), ('base_datos', 'Base de datos')], default='noticia', max_length=20),
        ),
    ]
