# Generated by Django 5.2.16 on 2026-08-31 23:02

import apps.core.almacenamiento
import apps.core.validadores
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenidos', '0006_alter_noticia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticiaArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Queda accesible por su URL en cuanto guardas, aunque la noticia siga en borrador. No subas aquí nada reservado.', upload_to=apps.core.almacenamiento.ruta_adjunto, validators=[apps.core.validadores.validar_adjunto])),
                ('titulo', models.CharField(help_text='Lo que se lee en la ficha.', max_length=200)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('peso_bytes', models.PositiveBigIntegerField(default=0, editable=False)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='contenidos.noticia')),
            ],
            options={
                'verbose_name': 'archivo de la noticia',
                'verbose_name_plural': 'archivos',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NoticiaEnlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Lo que se lee en la ficha.', max_length=200)),
                ('url', models.URLField(max_length=500)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enlaces', to='contenidos.noticia')),
            ],
            options={
                'verbose_name': 'enlace de la noticia',
                'verbose_name_plural': 'enlaces',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
