# Generated by Django 5.2.16 on 2026-08-03 17:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        ('peligros', '0001_initial'),
        ('territorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.', verbose_name='nota de revisión')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('ambito', models.CharField(choices=[('comunal', 'Comunal'), ('distrital', 'Distrital'), ('provincial', 'Provincial'), ('regional', 'Regional')], max_length=12, verbose_name='ámbito')),
                ('resultado', models.CharField(choices=[('exito', 'Éxito'), ('leccion', 'Lección aprendida'), ('mal_adaptacion', 'Mala adaptación')], db_index=True, max_length=16)),
                ('comunidad', models.CharField(blank=True, max_length=150)),
                ('resumen_corto', models.TextField(max_length=500, verbose_name='resumen corto')),
                ('contenido', models.TextField(blank=True, help_text='HTML de CKEditor 5. Se sanea al guardar (ADR-D2).')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL del video')),
                ('imagen_portada', models.ImageField(blank=True, help_text='Si lo dejas vacío se usa la ilustración institucional del peligro.', null=True, upload_to='medidas/%Y/%m/')),
                ('imagen_titulo', models.CharField(blank=True, help_text='Se muestra debajo de la portada.', max_length=300, verbose_name='pie de la imagen')),
                ('palabras_clave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='palabras clave')),
                ('enlaces', models.JSONField(blank=True, default=list, help_text='Lista de {"titulo": …, "url": …}.')),
                ('destacada', models.BooleanField(default=False)),
                ('fecha_implementacion', models.DateField(blank=True, null=True)),
                ('actores', models.CharField(blank=True, max_length=300)),
                ('costo_referencial', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('centro_poblado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas', to='territorio.centropoblado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('distrito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medidas', to='territorio.distrito')),
                ('documentos', models.ManyToManyField(blank=True, related_name='medidas', to='biblioteca.documento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tipo_peligro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='medidas', to='peligros.tipopeligro')),
            ],
            options={
                'verbose_name': 'medida',
                'ordering': ['-publicado_en', '-creado_en'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar medidas')],
            },
        ),
        migrations.CreateModel(
            name='MedidaImagen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('imagen', models.ImageField(upload_to='medidas/%Y/%m/')),
                ('pie', models.CharField(max_length=300)),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='medidas.medida')),
            ],
            options={
                'verbose_name': 'imagen de la medida',
                'verbose_name_plural': 'galería',
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='medida',
            index=models.Index(fields=['estado', '-publicado_en'], name='medidas_med_estado_c8dec1_idx'),
        ),
        migrations.AddConstraint(
            model_name='medidaimagen',
            constraint=models.UniqueConstraint(fields=('medida', 'orden'), name='unico_orden_galeria_medida'),
        ),
    ]
