# Generated by Django 5.2.16 on 2026-08-27 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medida',
            name='ambito',
            field=models.CharField(choices=[('comunal', 'Comunal'), ('distrital', 'Distrital'), ('provincial', 'Provincial'), ('regional', 'Regional')], max_length=12, verbose_name='Alcance de la experiencia'),
        ),
    ]
