# Generated by Django 5.2.16 on 2026-08-27 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0002_alter_medida_ambito'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedidaFichaACC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('value_001', models.TextField(verbose_name='Nombre de la experiencia, práctica proyecto o programa')),
                ('value_002', models.TextField(blank=True, default='', help_text='Indicar: Departamento / Provincia / Distrito / Comunidad Donde se implementó o implementa', verbose_name='Ubicación')),
                ('value_003', models.TextField(help_text='vacio', verbose_name='Institución u organización responsable de la ejecución')),
                ('value_004', models.TextField(blank=True, default='', help_text='Se considera a la persona que puede aclarar dudas Respecto a la experiencia.', verbose_name='Persona de contacto: nombre, cargo, teléfono y correo')),
                ('value_005', models.TextField(help_text='Indicar la fecha de inicio y cierre de la practica', verbose_name='Periodo de tiempo de la implementación')),
                ('value_006', models.TextField(help_text='Marcar una o más opciones', verbose_name='¿Qué peligros o amenazas naturales atiende esta práctica?')),
                ('value_007', models.TextField(help_text='Describa brevemente la problemática en relación con la Manifestación de los impactos del peligro que atiende Esta práctica (máx. 5 líneas)', verbose_name='Descripción del problema')),
                ('value_008', models.TextField(blank=True, default='', help_text='Describa brevemente en qué consiste la práctica, cómo funciona y qué medidas se han implementado (máx. 10 líneas)', verbose_name='Descripción de la práctica, experiencia, programa o proyecto')),
                ('value_009', models.TextField(help_text='Indique con qué enfoque se relaciona con mayor cercanía. Puede marcar más de una opción', verbose_name='Enfoque de la práctica, experiencia, programa o proyecto')),
                ('value_010', models.TextField(help_text='indique hasta 3 saberes ancestrales y 3 prácticas de enfoque de género', verbose_name='La práctica incorpora saberes ancestrales y enfoque de género? ¿Cuáles?')),
                ('value_011', models.TextField(help_text='Describe los resultados clave, de preferencia utilizando cifras: Nº de personas / familias beneficiadas, hectáreas, litros de agua almacenada, etc.', verbose_name='Resultados cuantitativos o beneficios logrados con la práctica, experiencia, programa o proyecto')),
                ('value_012', models.TextField(help_text='Describe brevemente los cambios positivos que ha generado el proyecto: en el comportamiento de sus beneficiarios, actitudes, prácticas, conocimientos, etc.', verbose_name='Resultados cualitativos o beneficios logrados con la práctica, experiencia, programa o proyecto')),
                ('value_013', models.TextField(help_text='Indicar el monto aproximado en soles y fuente (institución, programa, otro)', verbose_name='Costo aproximado de la implementación y fuente de financiamiento')),
                ('value_014', models.TextField(help_text='Indica al menos 3 factores que han contribuido a que la práctica se desarrolle con éxito (por ejemplo: participación activa de las comunidades, articulación con gobiernos locales y otras organizaciones, etc)', verbose_name='Principales factores de éxito')),
                ('value_015', models.TextField(help_text='Indica al menos 3 lecciones aprendidas claves a resaltar y tener en cuenta al replicar este tipo de intervención', verbose_name='Principales lecciones aprendidas')),
                ('value_016', models.TextField(help_text='Describir brevemente si es una persona, entidad o comunidad, e indicar el rol que cumplen.', verbose_name='¿Quién se encarga de mantener o gestionar actualmente la práctica?')),
                ('value_017', models.TextField(help_text='Indicar brevemente por qué es replicable y qué necesitaría par serlo. Por ejemplo: Costos accesibles, participación comunitaria, resultados demostrados.', verbose_name='¿Es replicable en otras comunidades? ¿Qué se necesitaría para replicarla?')),
                ('medida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichas_acc', to='medidas.medida')),
            ],
            options={
                'verbose_name': 'ficha de Adaptación al Cambio Climático',
                'verbose_name_plural': 'fichas de Adaptación al Cambio Climático',
            },
        ),
    ]
