# Generated by Django 5.2.16 on 2026-08-27 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medidas', '0003_medidafichaacc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='medidafichaacc',
            options={'verbose_name': 'Ficha de Adaptación al Cambio Climático', 'verbose_name_plural': 'fichas de Adaptación al Cambio Climático'},
        ),
        migrations.AlterField(
            model_name='medidafichaacc',
            name='value_003',
            field=models.TextField(verbose_name='Institución u organización responsable de la ejecución'),
        ),
    ]
