# Generated by Django 5.2.16 on 2026-08-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Una medida puede nacer de una ficha ACC (ADR-D10).

    Añade la procedencia (`ficha_acc`) y los tres campos de estado de `core.EstadoIAMixin`, y
    **hace `tipo_peligro` nullable**, que es lo único con consecuencias fuera de esta app.

    El motivo: con la casilla «Procesar con IA» marcada, la medida se guarda al instante con el
    formulario casi vacío, y `tipo_peligro` era el único obligatorio que no podía guardarse como
    cadena vacía. Replegarlo a un peligro cualquiera habría puesto una clasificación falsa que
    nadie revisaría —el campo se vería lleno—, que es lo que ADR-D8 ya decidió no hacer.

    Un borrador puede estar incompleto; lo publicado no: `Medida.faltantes_para_publicar()` lo
    exige de vuelta al pasar a «publicado», y hay pruebas que lo fijan.

    Los dos `verbose_name` («título», «tipo de peligro») no son cosmética: el mensaje que ve el
    editor cuando no puede publicar se compone con ellos, y «Falta completar: titulo, tipo
    peligro» no es una frase que se le pueda enseñar a nadie.

    **No emite nada para `contenidos` ni `normativa`** aunque `RedaccionIAMixin` se partió en dos
    bases abstractas: los campos que aportan a `Noticia` y `Norma` son los mismos y el
    autodetector no reacciona a un cambio de orden. Hay una prueba que lo comprueba.
    """


    dependencies = [
        ('medidas', '0006_alter_medidafichaacc_options_and_more'),
        ('peligros', '0002_alter_tipopeligro_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='medida',
            name='ficha_acc',
            field=models.ForeignKey(blank=True, help_text='Ficha de la que la IA redactó esta medida. Queda como procedencia.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medidas', to='medidas.medidafichaacc', verbose_name='ficha ACC de origen'),
        ),
        migrations.AddField(
            model_name='medida',
            name='ia_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('procesando', 'Procesando'), ('ok', 'Generado'), ('error', 'Error')], default='pendiente', max_length=12, verbose_name='estado de la IA'),
        ),
        migrations.AddField(
            model_name='medida',
            name='log_ia',
            field=models.TextField(blank=True, verbose_name='registro de la IA'),
        ),
        migrations.AddField(
            model_name='medida',
            name='redactada_por_ia',
            field=models.BooleanField(default=False, verbose_name='redactada por IA'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='tipo_peligro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='medidas', to='peligros.tipopeligro', verbose_name='tipo de peligro'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='título'),
        ),
    ]
