# Generated by Django 5.2.16 on 2026-08-03 17:08

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('biblioteca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Norma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En revisión'), ('publicado', 'Publicado'), ('archivado', 'Archivado')], db_index=True, default='borrador', max_length=12)),
                ('publicado_en', models.DateTimeField(blank=True, null=True)),
                ('nota_revision', models.TextField(blank=True, help_text='Comentario del revisor al devolver el contenido a borrador.', verbose_name='nota de revisión')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('titulo', models.CharField(max_length=300)),
                ('tipo', models.CharField(choices=[('Ley', 'Ley'), ('DS', 'Decreto Supremo'), ('RM', 'Resolución Ministerial'), ('RJ', 'Resolución Jefatural'), ('Ordenanza', 'Ordenanza')], max_length=12)),
                ('ambito', models.CharField(choices=[('nacional', 'Nacional'), ('regional', 'Regional'), ('local', 'Local')], db_index=True, max_length=10, verbose_name='ámbito')),
                ('fecha', models.DateField(db_index=True)),
                ('resumen', models.TextField(max_length=700)),
                ('contenido', models.TextField(blank=True, help_text='Análisis desarrollado de la ficha (HTML de CKEditor 5, saneado al guardar).')),
                ('url_oficial', models.URLField(blank=True, null=True)),
                ('analisis_predes', models.TextField(blank=True, help_text='Nota breve que se muestra en el listado.', null=True, verbose_name='análisis de PREDES')),
                ('imagen_portada', models.ImageField(blank=True, help_text='Si lo dejas vacío se usa la ilustración institucional de normativa.', null=True, upload_to='normativa/%Y/%m/')),
                ('imagen_titulo', models.CharField(blank=True, max_length=300, verbose_name='pie de la imagen')),
                ('palabras_clave', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), blank=True, default=list, size=None, verbose_name='palabras clave')),
                ('numero', models.CharField(blank=True, help_text='P. ej. "DS 048-2011-PCM".', max_length=80)),
                ('estado_vigencia', models.CharField(blank=True, choices=[('vigente', 'Vigente'), ('derogada', 'Derogada'), ('modificada', 'Modificada')], max_length=12, verbose_name='estado de vigencia')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('documento', models.ForeignKey(blank=True, help_text='PDF alojado por PREDES. Vía preferente; habilita el resumen con IA.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normas', to='biblioteca.documento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'norma',
                'verbose_name_plural': 'normativa',
                'ordering': ['-fecha'],
                'permissions': [('puede_publicar', 'Puede publicar y archivar normas')],
                'indexes': [models.Index(fields=['estado', '-fecha'], name='normativa_n_estado_577a41_idx')],
            },
        ),
    ]
