# Generated by Django 5.2.16 on 2026-08-31 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0003_norma_ia_estado_norma_log_ia_norma_redactada_por_ia_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadEmisora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('sigla', models.CharField(blank=True, help_text='Abreviatura con la que se la conoce, p. ej. "PCM" o "MINAM". Es lo que se muestra en las tarjetas del listado, donde no cabe el nombre completo.', max_length=20)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('orden', models.PositiveSmallIntegerField(default=0, help_text='Las de menor número salen primero en el desplegable.')),
            ],
            options={
                'verbose_name': 'entidad emisora',
                'verbose_name_plural': 'entidades emisoras',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='norma',
            name='entidad_emisora',
            field=models.ForeignKey(blank=True, help_text='Institución que la dicta. Vacío si no consta.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normas', to='normativa.entidademisora', verbose_name='entidad emisora'),
        ),
    ]
